import os
print(" Welcome to LVM Creation ~")
print()
dev_name = input("Please enter the device name - ")
os.system(f'pvcreate {dev_name}')
vg_name = input("Please enter your VG name - ")
os.system(f'vgcreate {vg_name} {dev_name}')
os.system(f'vgdisplay {vg_name}')
lv_name = input("Please enter your LV name - ")
size = input("Please enter the size of LV - ")
os.system(f'lvcreate --size {size}G --name {lv_name} {vg_name}')
os.system(f'mkfs.ext4 /dev/{vg_name}/{lv_name}')
dir_name = input('Please enter the directory you want to mount the LV to -')
os.system(f'mount /dev/{vg_name}/{lv_name} {dir_name}')
